add support to php 8.1
kool-dev/docker-php-sqlsrv pull request #21
Opened 2022-12-19 18:34 UTC by souza-leonardo

Create Dockerfile to support PHP 8.1

2022-12-19 19:15 UTC, fabriciojs requested changes
Looking good! We just need to also update our CI to make sure we are building/testing/pushing the new image tag to Hub Docker.

https://github.com/kool-dev/docker-php-sqlsrv/blob/main/.github/workflows/ci-cd.yml#L17-L40

Ideally, we refactor that to a Matrix scheme that runs in parallel 7.4 and 8.1 images.

Also please update the `README` to include the new version/links.

2022-12-19 19:59 UTC, souza-leonardo commented
@fabriciojs the changes were made

2022-12-20 11:42 UTC, fabriciojs approved these changes

2022-12-20 11:42 UTC, merged

2022-12-20 11:43 UTC, fabriciojs commented
Thank you @souza-leonardo for the contribution!